import Navbar from '@/components/Navbar'
import { SelectedColorProvider } from '@/contexts/SelectedColorContext'
import { SelectedItemProvider } from '@/contexts/SelectedItemContext'
import { CategorySidebarProvider } from '@/contexts/CategorySidebarContext'
import '@/styles/global.css'
import localFont from 'next/font/local'

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${pretendard.variable}`}>
      <body className={`${pretendard.className}`}>
        <CategorySidebarProvider>
          <SelectedItemProvider>
            <SelectedColorProvider>
              <div className="py-20">
                {children}
                <Navbar />
              </div>
            </SelectedColorProvider>
          </SelectedItemProvider>
        </CategorySidebarProvider>
      </body>
    </html>
  )
}
