allprojects {
    group = 'com.ssafy.ozz'
    version = '0.0.1-SNAPSHOT'
}

subprojects {
    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs += '-parameters'
    }

    repositories {
        mavenCentral()
        maven {
            url = uri("file://${rootProject.projectDir}/library/build/repos")
        }
    }
}

task cleanAll {
    dependsOn ':auth:clean', ':user:clean', ':file-server:clean', ':clothes:clean',
            ':favorite:clean', ':board:clean', ':library:clean', ':monolith:clean'
}

task publishLibrary {
    dependsOn 'library:publish'
}

task buildAll {
    dependsOn ':monolith:bootJar'
}

task buildMonolith {
    dependsOn ':monolith:bootJar'
}
