plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.2'
    id 'io.spring.dependency-management' version '1.1.6'
}

ext {
    springCloudVersion = "2023.0.3"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencies {
    implementation(project(':auth')) {
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-starter-netflix-eureka-client'
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-starter-openfeign'
    }
    implementation(project(':user')) {
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-starter-netflix-eureka-client'
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-starter-openfeign'
    }
    implementation(project(':file-server')) {
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-starter-netflix-eureka-client'
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-starter-openfeign'
    }
    implementation(project(':clothes')) {
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-starter-netflix-eureka-client'
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-starter-openfeign'
    }
    implementation(project(':favorite')) {
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-starter-netflix-eureka-client'
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-starter-openfeign'
    }
    implementation(project(':board')) {
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-starter-netflix-eureka-client'
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-starter-openfeign'
    }
    implementation project(':library')

    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'
    implementation 'io.micrometer:micrometer-registry-prometheus'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    developmentOnly 'com.h2database:h2'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
