apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ozz

resources:
  - namespace.yaml
  - configmap.yaml
  - infra.yaml
  - apps.yaml
  - ingress.yaml

images:
  - name: ozz/eureka
    newTag: dev
  - name: ozz/gateway
    newTag: dev
  - name: ozz/auth
    newTag: dev
  - name: ozz/user
    newTag: dev
  - name: ozz/clothes
    newTag: dev
  - name: ozz/favorite
    newTag: dev
  - name: ozz/board
    newTag: dev
  - name: ozz/file-server
    newTag: dev
  - name: ozz/ai
    newTag: dev
  - name: ozz/frontend
    newTag: dev
